services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinect-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3001/api/v1}
      NEXT_PUBLIC_APP_NAME: CinemaConnect
      NEXT_PUBLIC_ENV: production
